//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageHeader", Namespace="http://api.onnorokomsms.com/")]
    public partial class MessageHeader : object
    {
        
        private string UserNameField;
        
        private string UserPasswordField;
        
        private string MarskTextField;
        
        private string CampingNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserPassword
        {
            get
            {
                return this.UserPasswordField;
            }
            set
            {
                this.UserPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MarskText
        {
            get
            {
                return this.MarskTextField;
            }
            set
            {
                this.MarskTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CampingName
        {
            get
            {
                return this.CampingNameField;
            }
            set
            {
                this.CampingNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WsSms", Namespace="http://api.onnorokomsms.com/")]
    public partial class WsSms : object
    {
        
        private string MobileNumberField;
        
        private string SmsTextField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SmsText
        {
            get
            {
                return this.SmsTextField;
            }
            set
            {
                this.SmsTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.onnorokomsms.com/", ConfigurationName="ServiceReference1.SendSmsSoap")]
    public interface SendSmsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToOneBulk", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.OneToOneBulkResponse> OneToOneBulkAsync(ServiceReference1.OneToOneBulkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToOne", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.OneToOneResponse> OneToOneAsync(ServiceReference1.OneToOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToMany", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.OneToManyResponse> OneToManyAsync(ServiceReference1.OneToManyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/DeliveryStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.DeliveryStatusResponse> DeliveryStatusAsync(ServiceReference1.DeliveryStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetBalanceResponse> GetBalanceAsync(ServiceReference1.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetMask", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetMaskResponse> GetMaskAsync(ServiceReference1.GetMaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/NumberSms", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.NumberSmsResponse> NumberSmsAsync(ServiceReference1.NumberSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/ListSms", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListSmsResponse> ListSmsAsync(ServiceReference1.ListSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/SMSDeliveryStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SMSDeliveryStatusResponse> SMSDeliveryStatusAsync(ServiceReference1.SMSDeliveryStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetCurrentBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetCurrentBalanceResponse> GetCurrentBalanceAsync(ServiceReference1.GetCurrentBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetAllMask", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetAllMaskResponse> GetAllMaskAsync(ServiceReference1.GetAllMaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetRates", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetRatesResponse> GetRatesAsync(ServiceReference1.GetRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetVersionResponse> GetVersionAsync(ServiceReference1.GetVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneBulkRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOneBulk", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.OneToOneBulkRequestBody Body;
        
        public OneToOneBulkRequest()
        {
        }
        
        public OneToOneBulkRequest(ServiceReference1.OneToOneBulkRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneBulkRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.MessageHeader messageHeader;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.WsSms[] wsSmses;
        
        public OneToOneBulkRequestBody()
        {
        }
        
        public OneToOneBulkRequestBody(ServiceReference1.MessageHeader messageHeader, ServiceReference1.WsSms[] wsSmses)
        {
            this.messageHeader = messageHeader;
            this.wsSmses = wsSmses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneBulkResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOneBulkResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.OneToOneBulkResponseBody Body;
        
        public OneToOneBulkResponse()
        {
        }
        
        public OneToOneBulkResponse(ServiceReference1.OneToOneBulkResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneBulkResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OneToOneBulkResult;
        
        public OneToOneBulkResponseBody()
        {
        }
        
        public OneToOneBulkResponseBody(string OneToOneBulkResult)
        {
            this.OneToOneBulkResult = OneToOneBulkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOne", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.OneToOneRequestBody Body;
        
        public OneToOneRequest()
        {
        }
        
        public OneToOneRequest(ServiceReference1.OneToOneRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobileNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string campaignName;
        
        public OneToOneRequestBody()
        {
        }
        
        public OneToOneRequestBody(string userName, string userPassword, string mobileNumber, string smsText, string type, string maskName, string campaignName)
        {
            this.userName = userName;
            this.userPassword = userPassword;
            this.mobileNumber = mobileNumber;
            this.smsText = smsText;
            this.type = type;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOneResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.OneToOneResponseBody Body;
        
        public OneToOneResponse()
        {
        }
        
        public OneToOneResponse(ServiceReference1.OneToOneResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OneToOneResult;
        
        public OneToOneResponseBody()
        {
        }
        
        public OneToOneResponseBody(string OneToOneResult)
        {
            this.OneToOneResult = OneToOneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToManyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToMany", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.OneToManyRequestBody Body;
        
        public OneToManyRequest()
        {
        }
        
        public OneToManyRequest(ServiceReference1.OneToManyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToManyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string numberList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string smsType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string campaignName;
        
        public OneToManyRequestBody()
        {
        }
        
        public OneToManyRequestBody(string userName, string userPassword, string messageText, string numberList, string smsType, string maskName, string campaignName)
        {
            this.userName = userName;
            this.userPassword = userPassword;
            this.messageText = messageText;
            this.numberList = numberList;
            this.smsType = smsType;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToManyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToManyResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.OneToManyResponseBody Body;
        
        public OneToManyResponse()
        {
        }
        
        public OneToManyResponse(ServiceReference1.OneToManyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToManyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OneToManyResult;
        
        public OneToManyResponseBody()
        {
        }
        
        public OneToManyResponseBody(string OneToManyResult)
        {
            this.OneToManyResult = OneToManyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeliveryStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeliveryStatus", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.DeliveryStatusRequestBody Body;
        
        public DeliveryStatusRequest()
        {
        }
        
        public DeliveryStatusRequest(ServiceReference1.DeliveryStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class DeliveryStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string responseId;
        
        public DeliveryStatusRequestBody()
        {
        }
        
        public DeliveryStatusRequestBody(string userName, string userPassword, string responseId)
        {
            this.userName = userName;
            this.userPassword = userPassword;
            this.responseId = responseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeliveryStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeliveryStatusResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.DeliveryStatusResponseBody Body;
        
        public DeliveryStatusResponse()
        {
        }
        
        public DeliveryStatusResponse(ServiceReference1.DeliveryStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class DeliveryStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeliveryStatusResult;
        
        public DeliveryStatusResponseBody()
        {
        }
        
        public DeliveryStatusResponseBody(string DeliveryStatusResult)
        {
            this.DeliveryStatusResult = DeliveryStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetBalanceRequestBody Body;
        
        public GetBalanceRequest()
        {
        }
        
        public GetBalanceRequest(ServiceReference1.GetBalanceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetBalanceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        public GetBalanceRequestBody()
        {
        }
        
        public GetBalanceRequestBody(string userName, string userPassword)
        {
            this.userName = userName;
            this.userPassword = userPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetBalanceResponseBody Body;
        
        public GetBalanceResponse()
        {
        }
        
        public GetBalanceResponse(ServiceReference1.GetBalanceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetBalanceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBalanceResult;
        
        public GetBalanceResponseBody()
        {
        }
        
        public GetBalanceResponseBody(string GetBalanceResult)
        {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaskRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMask", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetMaskRequestBody Body;
        
        public GetMaskRequest()
        {
        }
        
        public GetMaskRequest(ServiceReference1.GetMaskRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetMaskRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        public GetMaskRequestBody()
        {
        }
        
        public GetMaskRequestBody(string userName, string userPassword)
        {
            this.userName = userName;
            this.userPassword = userPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaskResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMaskResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetMaskResponseBody Body;
        
        public GetMaskResponse()
        {
        }
        
        public GetMaskResponse(ServiceReference1.GetMaskResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetMaskResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMaskResult;
        
        public GetMaskResponseBody()
        {
        }
        
        public GetMaskResponseBody(string GetMaskResult)
        {
            this.GetMaskResult = GetMaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberSms", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.NumberSmsRequestBody Body;
        
        public NumberSmsRequest()
        {
        }
        
        public NumberSmsRequest(ServiceReference1.NumberSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class NumberSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string messageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numberList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string campaignName;
        
        public NumberSmsRequestBody()
        {
        }
        
        public NumberSmsRequestBody(string apiKey, string messageText, string numberList, string smsType, string maskName, string campaignName)
        {
            this.apiKey = apiKey;
            this.messageText = messageText;
            this.numberList = numberList;
            this.smsType = smsType;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberSmsResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.NumberSmsResponseBody Body;
        
        public NumberSmsResponse()
        {
        }
        
        public NumberSmsResponse(ServiceReference1.NumberSmsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class NumberSmsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberSmsResult;
        
        public NumberSmsResponseBody()
        {
        }
        
        public NumberSmsResponseBody(string NumberSmsResult)
        {
            this.NumberSmsResult = NumberSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListSms", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.ListSmsRequestBody Body;
        
        public ListSmsRequest()
        {
        }
        
        public ListSmsRequest(ServiceReference1.ListSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class ListSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.WsSms[] wsSmses;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string campaignName;
        
        public ListSmsRequestBody()
        {
        }
        
        public ListSmsRequestBody(string apiKey, ServiceReference1.WsSms[] wsSmses, string maskName, string campaignName)
        {
            this.apiKey = apiKey;
            this.wsSmses = wsSmses;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListSmsResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.ListSmsResponseBody Body;
        
        public ListSmsResponse()
        {
        }
        
        public ListSmsResponse(ServiceReference1.ListSmsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class ListSmsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListSmsResult;
        
        public ListSmsResponseBody()
        {
        }
        
        public ListSmsResponseBody(string ListSmsResult)
        {
            this.ListSmsResult = ListSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMSDeliveryStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMSDeliveryStatus", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.SMSDeliveryStatusRequestBody Body;
        
        public SMSDeliveryStatusRequest()
        {
        }
        
        public SMSDeliveryStatusRequest(ServiceReference1.SMSDeliveryStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class SMSDeliveryStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string responseId;
        
        public SMSDeliveryStatusRequestBody()
        {
        }
        
        public SMSDeliveryStatusRequestBody(string apiKey, string responseId)
        {
            this.apiKey = apiKey;
            this.responseId = responseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMSDeliveryStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMSDeliveryStatusResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.SMSDeliveryStatusResponseBody Body;
        
        public SMSDeliveryStatusResponse()
        {
        }
        
        public SMSDeliveryStatusResponse(ServiceReference1.SMSDeliveryStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class SMSDeliveryStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMSDeliveryStatusResult;
        
        public SMSDeliveryStatusResponseBody()
        {
        }
        
        public SMSDeliveryStatusResponseBody(string SMSDeliveryStatusResult)
        {
            this.SMSDeliveryStatusResult = SMSDeliveryStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentBalance", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetCurrentBalanceRequestBody Body;
        
        public GetCurrentBalanceRequest()
        {
        }
        
        public GetCurrentBalanceRequest(ServiceReference1.GetCurrentBalanceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetCurrentBalanceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public GetCurrentBalanceRequestBody()
        {
        }
        
        public GetCurrentBalanceRequestBody(string apiKey)
        {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentBalanceResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetCurrentBalanceResponseBody Body;
        
        public GetCurrentBalanceResponse()
        {
        }
        
        public GetCurrentBalanceResponse(ServiceReference1.GetCurrentBalanceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetCurrentBalanceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentBalanceResult;
        
        public GetCurrentBalanceResponseBody()
        {
        }
        
        public GetCurrentBalanceResponseBody(string GetCurrentBalanceResult)
        {
            this.GetCurrentBalanceResult = GetCurrentBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMaskRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMask", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetAllMaskRequestBody Body;
        
        public GetAllMaskRequest()
        {
        }
        
        public GetAllMaskRequest(ServiceReference1.GetAllMaskRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetAllMaskRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public GetAllMaskRequestBody()
        {
        }
        
        public GetAllMaskRequestBody(string apiKey)
        {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMaskResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMaskResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetAllMaskResponseBody Body;
        
        public GetAllMaskResponse()
        {
        }
        
        public GetAllMaskResponse(ServiceReference1.GetAllMaskResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetAllMaskResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllMaskResult;
        
        public GetAllMaskResponseBody()
        {
        }
        
        public GetAllMaskResponseBody(string GetAllMaskResult)
        {
            this.GetAllMaskResult = GetAllMaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRatesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRates", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetRatesRequestBody Body;
        
        public GetRatesRequest()
        {
        }
        
        public GetRatesRequest(ServiceReference1.GetRatesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetRatesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public GetRatesRequestBody()
        {
        }
        
        public GetRatesRequestBody(string apiKey)
        {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRatesResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetRatesResponseBody Body;
        
        public GetRatesResponse()
        {
        }
        
        public GetRatesResponse(ServiceReference1.GetRatesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetRatesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRatesResult;
        
        public GetRatesResponseBody()
        {
        }
        
        public GetRatesResponseBody(string GetRatesResult)
        {
            this.GetRatesResult = GetRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetVersionRequestBody Body;
        
        public GetVersionRequest()
        {
        }
        
        public GetVersionRequest(ServiceReference1.GetVersionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetVersionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public GetVersionRequestBody()
        {
        }
        
        public GetVersionRequestBody(string apiKey)
        {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public ServiceReference1.GetVersionResponseBody Body;
        
        public GetVersionResponse()
        {
        }
        
        public GetVersionResponse(ServiceReference1.GetVersionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetVersionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVersionResult;
        
        public GetVersionResponseBody()
        {
        }
        
        public GetVersionResponseBody(string GetVersionResult)
        {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface SendSmsSoapChannel : ServiceReference1.SendSmsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class SendSmsSoapClient : System.ServiceModel.ClientBase<ServiceReference1.SendSmsSoap>, ServiceReference1.SendSmsSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendSmsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SendSmsSoapClient.GetBindingForEndpoint(endpointConfiguration), SendSmsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSmsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendSmsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSmsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendSmsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSmsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.OneToOneBulkResponse> ServiceReference1.SendSmsSoap.OneToOneBulkAsync(ServiceReference1.OneToOneBulkRequest request)
        {
            return base.Channel.OneToOneBulkAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.OneToOneBulkResponse> OneToOneBulkAsync(ServiceReference1.MessageHeader messageHeader, ServiceReference1.WsSms[] wsSmses)
        {
            ServiceReference1.OneToOneBulkRequest inValue = new ServiceReference1.OneToOneBulkRequest();
            inValue.Body = new ServiceReference1.OneToOneBulkRequestBody();
            inValue.Body.messageHeader = messageHeader;
            inValue.Body.wsSmses = wsSmses;
            return ((ServiceReference1.SendSmsSoap)(this)).OneToOneBulkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.OneToOneResponse> ServiceReference1.SendSmsSoap.OneToOneAsync(ServiceReference1.OneToOneRequest request)
        {
            return base.Channel.OneToOneAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.OneToOneResponse> OneToOneAsync(string userName, string userPassword, string mobileNumber, string smsText, string type, string maskName, string campaignName)
        {
            ServiceReference1.OneToOneRequest inValue = new ServiceReference1.OneToOneRequest();
            inValue.Body = new ServiceReference1.OneToOneRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.mobileNumber = mobileNumber;
            inValue.Body.smsText = smsText;
            inValue.Body.type = type;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((ServiceReference1.SendSmsSoap)(this)).OneToOneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.OneToManyResponse> ServiceReference1.SendSmsSoap.OneToManyAsync(ServiceReference1.OneToManyRequest request)
        {
            return base.Channel.OneToManyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.OneToManyResponse> OneToManyAsync(string userName, string userPassword, string messageText, string numberList, string smsType, string maskName, string campaignName)
        {
            ServiceReference1.OneToManyRequest inValue = new ServiceReference1.OneToManyRequest();
            inValue.Body = new ServiceReference1.OneToManyRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.messageText = messageText;
            inValue.Body.numberList = numberList;
            inValue.Body.smsType = smsType;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((ServiceReference1.SendSmsSoap)(this)).OneToManyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DeliveryStatusResponse> ServiceReference1.SendSmsSoap.DeliveryStatusAsync(ServiceReference1.DeliveryStatusRequest request)
        {
            return base.Channel.DeliveryStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DeliveryStatusResponse> DeliveryStatusAsync(string userName, string userPassword, string responseId)
        {
            ServiceReference1.DeliveryStatusRequest inValue = new ServiceReference1.DeliveryStatusRequest();
            inValue.Body = new ServiceReference1.DeliveryStatusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.responseId = responseId;
            return ((ServiceReference1.SendSmsSoap)(this)).DeliveryStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetBalanceResponse> ServiceReference1.SendSmsSoap.GetBalanceAsync(ServiceReference1.GetBalanceRequest request)
        {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBalanceResponse> GetBalanceAsync(string userName, string userPassword)
        {
            ServiceReference1.GetBalanceRequest inValue = new ServiceReference1.GetBalanceRequest();
            inValue.Body = new ServiceReference1.GetBalanceRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            return ((ServiceReference1.SendSmsSoap)(this)).GetBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetMaskResponse> ServiceReference1.SendSmsSoap.GetMaskAsync(ServiceReference1.GetMaskRequest request)
        {
            return base.Channel.GetMaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetMaskResponse> GetMaskAsync(string userName, string userPassword)
        {
            ServiceReference1.GetMaskRequest inValue = new ServiceReference1.GetMaskRequest();
            inValue.Body = new ServiceReference1.GetMaskRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            return ((ServiceReference1.SendSmsSoap)(this)).GetMaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.NumberSmsResponse> ServiceReference1.SendSmsSoap.NumberSmsAsync(ServiceReference1.NumberSmsRequest request)
        {
            return base.Channel.NumberSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.NumberSmsResponse> NumberSmsAsync(string apiKey, string messageText, string numberList, string smsType, string maskName, string campaignName)
        {
            ServiceReference1.NumberSmsRequest inValue = new ServiceReference1.NumberSmsRequest();
            inValue.Body = new ServiceReference1.NumberSmsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.messageText = messageText;
            inValue.Body.numberList = numberList;
            inValue.Body.smsType = smsType;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((ServiceReference1.SendSmsSoap)(this)).NumberSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ListSmsResponse> ServiceReference1.SendSmsSoap.ListSmsAsync(ServiceReference1.ListSmsRequest request)
        {
            return base.Channel.ListSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListSmsResponse> ListSmsAsync(string apiKey, ServiceReference1.WsSms[] wsSmses, string maskName, string campaignName)
        {
            ServiceReference1.ListSmsRequest inValue = new ServiceReference1.ListSmsRequest();
            inValue.Body = new ServiceReference1.ListSmsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.wsSmses = wsSmses;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((ServiceReference1.SendSmsSoap)(this)).ListSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SMSDeliveryStatusResponse> ServiceReference1.SendSmsSoap.SMSDeliveryStatusAsync(ServiceReference1.SMSDeliveryStatusRequest request)
        {
            return base.Channel.SMSDeliveryStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SMSDeliveryStatusResponse> SMSDeliveryStatusAsync(string apiKey, string responseId)
        {
            ServiceReference1.SMSDeliveryStatusRequest inValue = new ServiceReference1.SMSDeliveryStatusRequest();
            inValue.Body = new ServiceReference1.SMSDeliveryStatusRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.responseId = responseId;
            return ((ServiceReference1.SendSmsSoap)(this)).SMSDeliveryStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetCurrentBalanceResponse> ServiceReference1.SendSmsSoap.GetCurrentBalanceAsync(ServiceReference1.GetCurrentBalanceRequest request)
        {
            return base.Channel.GetCurrentBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetCurrentBalanceResponse> GetCurrentBalanceAsync(string apiKey)
        {
            ServiceReference1.GetCurrentBalanceRequest inValue = new ServiceReference1.GetCurrentBalanceRequest();
            inValue.Body = new ServiceReference1.GetCurrentBalanceRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((ServiceReference1.SendSmsSoap)(this)).GetCurrentBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetAllMaskResponse> ServiceReference1.SendSmsSoap.GetAllMaskAsync(ServiceReference1.GetAllMaskRequest request)
        {
            return base.Channel.GetAllMaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetAllMaskResponse> GetAllMaskAsync(string apiKey)
        {
            ServiceReference1.GetAllMaskRequest inValue = new ServiceReference1.GetAllMaskRequest();
            inValue.Body = new ServiceReference1.GetAllMaskRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((ServiceReference1.SendSmsSoap)(this)).GetAllMaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetRatesResponse> ServiceReference1.SendSmsSoap.GetRatesAsync(ServiceReference1.GetRatesRequest request)
        {
            return base.Channel.GetRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetRatesResponse> GetRatesAsync(string apiKey)
        {
            ServiceReference1.GetRatesRequest inValue = new ServiceReference1.GetRatesRequest();
            inValue.Body = new ServiceReference1.GetRatesRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((ServiceReference1.SendSmsSoap)(this)).GetRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetVersionResponse> ServiceReference1.SendSmsSoap.GetVersionAsync(ServiceReference1.GetVersionRequest request)
        {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetVersionResponse> GetVersionAsync(string apiKey)
        {
            ServiceReference1.GetVersionRequest inValue = new ServiceReference1.GetVersionRequest();
            inValue.Body = new ServiceReference1.GetVersionRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((ServiceReference1.SendSmsSoap)(this)).GetVersionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendSmsSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SendSmsSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendSmsSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api2.onnorokomsms.com/sendsms.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SendSmsSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api2.onnorokomsms.com/sendsms.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SendSmsSoap,
            
            SendSmsSoap12,
        }
    }
}
